add section in partrials html
vmorgunov/project-hellen pull request #6
Opened 2021-04-02 03:58 UTC by AngelikaLysenko

2021-04-02 10:08 UTC, vmorgunov requested changes

2021-04-02 10:08 UTC, vmorgunov commented on src/partials/how-we-do.html
> +    <div class="container__how-we-do">
измени на "container"

2021-04-02 10:08 UTC, vmorgunov commented on src/partials/how-we-do.html
> +        <h2 class="how-we-do__main-title">Как мы это делаем</h2>
"how-we-do__title"

2021-04-02 10:08 UTC, vmorgunov commented on src/partials/how-we-do.html
> +                <div class="how-we-do__icon">
убрать все div how-we-do__icon и добавить классы на svg

2021-04-02 10:08 UTC, vmorgunov commented on src/partials/how-we-do.html
> +                <div class="how-we-do__content">
убери все how-we-do_content

2021-04-02 10:09 UTC, Kseniia-FS approved these changes

2021-04-02 13:28 UTC, vmorgunov commented on src/partials/how-we-do.html
> +<section class="section__how-we-do">
замени на how-we-do

2021-04-02 20:48 UTC, vmorgunov requested changes

2021-04-02 20:48 UTC, vmorgunov commented on src/partials/how-we-do.html
> +<section Id="how-we-do">
добавь class="how-we-do"

2021-04-03 06:23 UTC, vmorgunov approved these changes

2021-04-03 06:25 UTC, merged